baseURL: "https://zorzeus.github.io/"
title: Đorđe Mijović
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: 
          weight: 6

params:
    description: ""
    
    author:
      name: ""
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, papers, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: ""
          subtitle: ""
          imageUrl: ""
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Old courses
              url: "https://zorzeus.github.io/old-faculty-site/"
            - name: Tags
              url: tags/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: "mailto:powaqqatsi98@proton.me"
        - name: Zoom
          url: "https://us04web.zoom.us/j/73715493279?pwd=ofUAXISMkZpwx4T3OA2oefIbRaNsFO.1"
        - name: Location
          url: "https://maps.app.goo.gl/bAFRfhbMy3zXFrf77"
        - name: Google Scholar
          url: ""
        - name: GitHub
          url: "https://github.com/zorzeus"
        - name: YouTube
          url: "https://www.youtube.com/@zorzeus"
        - name: Bluesky
          url: "https://bsky.app/profile/dordeus.bsky.social"

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: ""
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2